from enum import IntEnum, StrEnum


class DungeonKind(StrEnum):
    LIGHT = "light"
    SHADOW = "shadow"
    TOWER = "tower"
    TWISTER = "twister"


class LightDungeon(IntEnum):
    DESECRATED_CATACOMBS = 0
    MINES_OF_GLORIA = 1
    RUINS_OF_GNARK = 2
    CUTTHROAT_GROTTO = 3
    EMERALD_SCALE_ALTAR = 4
    TOXIC_TREE = 5
    MAGMA_STREAM = 6
    FROST_BLOOD_TEMPLE = 7
    PYRAMIDS_OF_MADNESS = 8
    BLACK_SKULL_FORTRESS = 9
    CIRCUS_OF_HORROR = 10
    HELL = 11
    THE_13TH_FLOOR = 12
    EASTEROS = 13
    TOWER = 14
    TIME_HONORED_SCHOOL_OF_MAGIC = 15
    HEMORRIDOR = 16
    # 17 is missing in light dungeons
    NORDIC_GODS = 18
    MOUNT_OLYMPUS = 19
    TAVERN_OF_THE_DARK_DOPPELGANGERS = 20
    DRAGONS_HOARD = 21
    HOUSE_OF_HORRORS = 22
    THIRD_LEAGUE_OF_SUPERHEROES = 23
    DOJO_OF_CHILDHOOD_HEROES = 24
    MONSTER_GROTTO = 25
    CITY_OF_INTRIGUES = 26
    SCHOOL_OF_MAGIC_EXPRESS = 27
    ASH_MOUNTAIN = 28
    PLAYA_GAMES_HQ = 29
    TRAINING_CAMP = 30
    SANDSTORM = 31
    ARCADE_OF_THE_OLD_PIXEL_ICONS = 32
    THE_SERVER_ROOM = 33
    WORKSHOP_OF_THE_HUNTERS = 34
    RETRO_TV_LEGENDS = 35
    MEETING_ROOM = 36


class ShadowDungeon(IntEnum):
    DESECRATED_CATACOMBS = 0
    MINES_OF_GLORIA = 1
    RUINS_OF_GNARK = 2
    CUTTHROAT_GROTTO = 3
    EMERALD_SCALE_ALTAR = 4
    TOXIC_TREE = 5
    MAGMA_STREAM = 6
    FROST_BLOOD_TEMPLE = 7
    PYRAMIDS_OF_MADNESS = 8
    BLACK_SKULL_FORTRESS = 9
    CIRCUS_OF_HORROR = 10
    HELL = 11
    THE_13TH_FLOOR = 12
    EASTEROS = 13
    TWISTER = 14
    TIME_HONORED_SCHOOL_OF_MAGIC = 15
    HEMORRIDOR = 16
    CONTINUOUS_LOOP_OF_IDOLS = 17
    NORDIC_GODS = 18
    MOUNT_OLYMPUS = 19
    TAVERN_OF_THE_DARK_DOPPELGANGERS = 20
    DRAGONS_HOARD = 21
    HOUSE_OF_HORRORS = 22
    THIRD_LEAGUE_OF_SUPERHEROES = 23
    DOJO_OF_CHILDHOOD_HEROES = 24
    MONSTER_GROTTO = 25
    CITY_OF_INTRIGUES = 26
    SCHOOL_OF_MAGIC_EXPRESS = 27
    ASH_MOUNTAIN = 28
    PLAYA_GAMES_HQ = 29
    # 30 (TrainingCamp) and 31 (Sandstorm) have no shadow version
    ARCADE_OF_THE_OLD_PIXEL_ICONS = 32
    THE_SERVER_ROOM = 33
    WORKSHOP_OF_THE_HUNTERS = 34
    RETRO_TV_LEGENDS = 35
    MEETING_ROOM = 36


class RuneType(IntEnum):
    NONE = 0
    FIRE = 40
    COLD = 41
    LIGHTNING = 42
