from sfbot.constants.enums import Attribute, CharClass
from sfbot.dungeon.enums import RuneType
from sfbot.dungeon.models import Fighter, Monster


def make_monster(
    char_class: CharClass = CharClass.WARRIOR,
    level: int = 100,
    strength: int = 1000,
    dexterity: int = 500,
    intelligence: int = 500,
    constitution: int = 800,
    luck: int = 400,
    armor: int = 200,
    min_dmg: int | None = 50,
    max_dmg: int | None = 100,
    health: int = 10_000,
    rune_type: int = 0,
    rune_damage: int = 0,
    fire_resistance: int = 0,
    cold_resistance: int = 0,
    lightning_resistance: int = 0,
    is_mirror: bool = False,
    name: str = "Test Monster",
) -> Monster:
    return Monster(
        name=name,
        char_class=char_class,
        level=level,
        strength=strength,
        dexterity=dexterity,
        intelligence=intelligence,
        constitution=constitution,
        luck=luck,
        armor=armor,
        min_dmg=min_dmg,
        max_dmg=max_dmg,
        health=health,
        rune_type=rune_type,
        rune_damage=rune_damage,
        fire_resistance=fire_resistance,
        cold_resistance=cold_resistance,
        lightning_resistance=lightning_resistance,
        is_mirror=is_mirror,
    )


def make_fighter(
    char_class: CharClass = CharClass.WARRIOR,
    level: int = 100,
    strength: int = 5000,
    dexterity: int = 1000,
    intelligence: int = 1000,
    constitution: int = 3000,
    luck: int = 2000,
    armor: int = 500,
    min_dmg: float = 100.0,
    max_dmg: float = 200.0,
    min_dmg2: float = 0.0,
    max_dmg2: float = 0.0,
    rune_type: RuneType = RuneType.NONE,
    rune_value: int = 0,
    fire_resistance: int = 0,
    cold_resistance: int = 0,
    lightning_resistance: int = 0,
    portal_hp_bonus: int = 0,
    portal_dmg_bonus: int = 0,
    rune_health: int = 0,
    gladiator: int = 0,
    has_sword_of_vengeance: bool = False,
    has_shadow_of_cowboy: bool = False,
    has_life_potion: bool = False,
    health: int = 0,
    is_companion: bool = False,
) -> Fighter:
    return Fighter(
        char_class=char_class,
        level=level,
        strength=strength,
        dexterity=dexterity,
        intelligence=intelligence,
        constitution=constitution,
        luck=luck,
        armor=armor,
        min_dmg=min_dmg,
        max_dmg=max_dmg,
        min_dmg2=min_dmg2,
        max_dmg2=max_dmg2,
        rune_type=rune_type,
        rune_value=rune_value,
        fire_resistance=fire_resistance,
        cold_resistance=cold_resistance,
        lightning_resistance=lightning_resistance,
        portal_hp_bonus=portal_hp_bonus,
        portal_dmg_bonus=portal_dmg_bonus,
        rune_health=rune_health,
        gladiator=gladiator,
        has_sword_of_vengeance=has_sword_of_vengeance,
        has_shadow_of_cowboy=has_shadow_of_cowboy,
        has_life_potion=has_life_potion,
        health=health,
        is_companion=is_companion,
    )


def make_attrs(
    strength: int = 5000,
    dexterity: int = 1000,
    intelligence: int = 1000,
    constitution: int = 3000,
    luck: int = 2000,
) -> dict[Attribute, int]:
    return {
        Attribute.STRENGTH: strength,
        Attribute.DEXTERITY: dexterity,
        Attribute.INTELLIGENCE: intelligence,
        Attribute.CONSTITUTION: constitution,
        Attribute.LUCK: luck,
    }
